using System;
using System.Collections.Generic;
using UnityEngine;

namespace InputPrompts
{
    /// <summary>
    /// All icons for one device family, keyed by control path (see <see cref="ControlPath.ToKey(string)"/>).
    /// Generated by <c>Tools &gt; Input Prompts &gt; Importer</c>, but hand-editable afterwards.
    /// </summary>
    [CreateAssetMenu(menuName = "Input Prompts/Prompt Set", fileName = "SO_InputPromptSet")]
    public class InputPromptSet : ScriptableObject
    {
        #region Public

        [Header("Device")]
        [Tooltip("Device family this set represents.")]
        public InputDeviceStyle m_style = InputDeviceStyle.Generic;

        [Tooltip("Layouts this set is used for, e.g. \"XInputController\". Checked against InputDevice.layout, sub-layouts included.")]
        public string[] m_layouts = Array.Empty<string>();

        [Space(15), Header("Icons")]
        [Tooltip("Used when a key has no icon of its own, e.g. a blank key cap the control name is printed on.")]
        public Sprite m_blankSprite;

        [Tooltip("When a key is missing here, look it up in this set instead.")]
        public InputPromptSet m_fallback;

        #endregion


        #region Private and Protected

        [SerializeField] private List<Entry> _entries = new();

        private Dictionary<string, Sprite> _lookup;

        #endregion


        #region Unity API

        private void OnValidate() => _lookup = null;

        #endregion


        #region Main API

        /// <summary>Every key/sprite pair of this set, in the order the importer wrote them.</summary>
        public IReadOnlyList<Entry> Entries => _entries;

        /// <summary>Icon for a control key, following <see cref="m_fallback"/> when this set has none.</summary>
        public Sprite Find(string key)
        {
            if (string.IsNullOrEmpty(key))
                return null;

            BuildLookup();
            if (_lookup.TryGetValue(key, out var sprite) && sprite != null)
                return sprite;

            return m_fallback != null && m_fallback != this ? m_fallback.Find(key) : null;
        }

        public bool Contains(string key)
        {
            if (string.IsNullOrEmpty(key))
                return false;

            BuildLookup();
            return _lookup.ContainsKey(key);
        }

        public void SetEntries(IEnumerable<Entry> entries)
        {
            _entries.Clear();
            _entries.AddRange(entries);
            _lookup = null;
        }

        /// <summary>Drops the cached lookup; call after editing <see cref="Entries"/> at runtime.</summary>
        public void Invalidate() => _lookup = null;

        #endregion


        #region Tools and Utilities

        private void BuildLookup()
        {
            if (_lookup != null)
                return;

            _lookup = new Dictionary<string, Sprite>(_entries.Count, StringComparer.Ordinal);
            foreach (var entry in _entries)
            {
                if (string.IsNullOrEmpty(entry.m_key))
                    continue;
                _lookup[entry.m_key.ToLowerInvariant()] = entry.m_sprite;
            }
        }

        #endregion

        [Serializable]
        public struct Entry
        {
            [Tooltip("Control path without the device part, e.g. \"space\", \"buttonSouth\", \"leftStick/up\".")]
            public string m_key;

            public Sprite m_sprite;
        }
    }
}
