using System;
using System.Collections.Generic;
using UnityEngine;

namespace Nekuz.InputPrompts
{
    /// <summary>
    /// All icons for one device family, keyed by control path (see <see cref="ControlPath.ToKey(string)"/>).
    /// Generated by <c>Tools &gt; Input Prompts &gt; Importer</c>, but hand-editable afterwards.
    /// </summary>
    [CreateAssetMenu(menuName = "Input Prompts/Prompt Set", fileName = "InputPromptSet")]
    public class InputPromptSet : ScriptableObject
    {
        [Serializable]
        public struct Entry
        {
            [Tooltip("Control path without the device part, e.g. \"space\", \"buttonSouth\", \"leftStick/up\".")]
            public string key;
            public Sprite sprite;
        }

        [Tooltip("Device family this set represents.")]
        public InputDeviceStyle style = InputDeviceStyle.Generic;

        [Tooltip("Layouts this set is used for, e.g. \"XInputController\". Checked against InputDevice.layout, sub-layouts included.")]
        public string[] layouts = Array.Empty<string>();

        [Tooltip("Used when a key has no icon of its own, e.g. a blank key cap the control's display name is printed on.")]
        public Sprite blankSprite;

        [Tooltip("When a key is missing here, look it up in this set instead.")]
        public InputPromptSet fallback;

        [SerializeField] private List<Entry> entries = new();

        private Dictionary<string, Sprite> _lookup;

        public IReadOnlyList<Entry> Entries => entries;

        /// <summary>Icon for a control key, following <see cref="fallback"/> when this set has none.</summary>
        public Sprite Find(string key)
        {
            if (string.IsNullOrEmpty(key))
                return null;

            BuildLookup();
            if (_lookup.TryGetValue(key, out var sprite) && sprite != null)
                return sprite;

            return fallback != null && fallback != this ? fallback.Find(key) : null;
        }

        public bool Contains(string key)
        {
            if (string.IsNullOrEmpty(key))
                return false;
            BuildLookup();
            return _lookup.ContainsKey(key);
        }

        public void SetEntries(IEnumerable<Entry> newEntries)
        {
            entries.Clear();
            entries.AddRange(newEntries);
            _lookup = null;
        }

        /// <summary>Drops the cached lookup; call after editing <see cref="Entries"/> at runtime.</summary>
        public void Invalidate() => _lookup = null;

        private void OnValidate() => _lookup = null;

        private void BuildLookup()
        {
            if (_lookup != null)
                return;

            _lookup = new Dictionary<string, Sprite>(entries.Count, StringComparer.Ordinal);
            foreach (var entry in entries)
            {
                if (string.IsNullOrEmpty(entry.key))
                    continue;
                _lookup[entry.key.ToLowerInvariant()] = entry.sprite;
            }
        }
    }
}
